### ISSUE TITLE
پروجەكىت رامكىسىنى قارار قىلىڭ

### ISSUE THREAD

**Issue by mayorvb** [tawush/teamwork#11]
مەن س ئەس قۇرۇلمىسىنى مۇۋاپىق كۆردۈم، ئىلگىرى ب ئەس نى ئويلاشقان، قانداقلا ئويلىسام س ئەس بىزگە ماس كەلگىدەك، مۇشۇنىڭغا قارىتا پىكىرىڭىزنى ئوتتۇرىغا قويۇڭ ۋە ئەڭ ئاخىرقى قارارنى سىز چىقىرىڭ
1. يۇقارقى قۇرۇلمىنى مۇقۇملاشتۇرۇڭ
2. سانداننى مۇقۇملاشتۇرۇڭ
3.تېرمىنال ياكى مۇلازىمىتىر ئىككى خىزمەتتىن بىرنى تاللاڭ
4. مەزكۇر مەسىلىنىڭ ۋاقتى مەزكۇر ئىشۇ يوللىنىپ 36 سائەت ئىچىدە تاماملانسۇن

@koznak مەزكۇر مەسىلە سىزگە يۈكلەندى

**Comment by koznak** [comment]
1. قۇرۇلما جەھەتتىن ب ئەس نى ئاساس قىلساق.
2. ساندانغا SQL Server نى تاللىساق.
3. مۇلازىمىتېر بۆلىكىنىڭ پروگراممىسىنى تاللاي.
