### ISSUE TITLE
2-نومۇرلۇق ۋەزىپە

### ISSUE THREAD

**Issue by mayorvb** [tawush/teamwork#2]
مەزكۇر مەسىلىنى پۈتتۈرۈپ ، مەسئۇلىيەتنى ماڭا يۈكلەڭ

**Comment by blip723** [comment]
Nima wazipa adax... bilal midim!??

**Comment by mayorvb** [comment]
@blip723 ئىنتايىن ياخشى، مەزكۇر ئىشۇ غا ئىنكاس قايتۇرغانلىقىڭنىڭ ئۆزى مەزكۇر مەسىلىنى ھەل قىلغىنىڭ شۇ، ئەمدى ماڭا مەسئۇلىيەتنى ئىتتىرىۋەتسەڭ تاماملىنىدۇ

**Comment by blip723** [comment]
سەن دىگەن يەرنى تاپالـمىدىم

**Comment by mayorvb** [comment]
@blip723 تېلېفون بېتىدە كۆرۈنمەيدۇ، شۇڭا سەن تېلېفون بېتىنىڭ ئوڭ تەرەپ ئەڭ ئاستىدىكى ئۈستەل يۈزى نۇسخىسى دېگەننى بېسىۋەتكىن

**Comment by mayorvb** [comment]
@blip723 ناھايىتى ياخشى، ساڭا ئۆگىتىش كەتمىدى، ئۆزەڭ ھەل قىلدىڭ، ئەمدى پەقەت بىرلا نۇقتا بار، ئۇ بولسىمۇ كىمگە سۆزلىسەڭ چوقۇم شۇنىڭغا ئەت قىلغان، يېشىق كىرگۈزۈش رامكىسنىڭ ئۈستىدە ئەت بەلگىسى بار

**Comment by mayorvb** [comment]
@blip723 خۇددى ماڭا ئوخشاش، مەن شۇتاپتا ساڭا ئەت قىلىپ ئۇچۇر يوللىدىم

**Comment by blip723** [comment]
ماقۇل ... بىلىۋالدىم

**Comment by blip723** [comment]
گۈزەل

**Comment by mayorvb** [comment]
@blip723 ئەت قىلمىدىڭ

**Comment by mayorvb** [comment]
@ مۇشۇ بەلگە

**Comment by blip723** [comment]
@mayorvb  @  nimu Qeldim mana ! amdi plan nil yaziman
