### ISSUE TITLE
جىددى !!! تېخنىكىغا تەۋە بولمىغان بىر ئايلىق خىزمەت

### ISSUE THREAD

**Issue by mayorvb** [tawush/teamwork#9]
تېخنىكىغا تەۋە بولمىغان ، ئەمما بۇ بىر ئاي ئىچىدە چوقۇم ھەل قىلىشقا تېگىشلىك خىزمەتلەر پۈتتۈرۈلۈش ۋاقتىنىڭ يېقىندىن ئۇزاققا تىزىلىشى بويىچە ئىنچىكە يېزىلسۇن، تولۇقلاپ تاپشۇرۇشقا بولىدۇ، ۋاقتى مەزكۇر ئىشۇ يوللىنىپ بىر يېرىم كۈن ئىچىدە تاماملانسۇن.

مەسىلەن:
1. يۇمشاق دېتال تۈرىنىڭ بازار ئېچىش بۆلىكى
2. مۇناسىۋەتلىك كىشىلەر بىلەن كۆرۈشۈپ مەكتەپنىڭ يېڭىچە ئەندىزىسىنى مۇقۇملاشتۇرۇش
3. چاقماقنىڭ تۈر پىلانىنى يېزىش
....
....

@blip723 بۇ مەسئۇلىيەت سىزگە يۈكلەندى

**Comment by blip723** [comment]
كەلگۈسى 1 ئاي  يەنى ئاۋغۇستنىڭ 1-كۈنىدىن ،سىنتەبىرنىڭ 1 كۈنىگچە پۈتتۈرۈشكە  تىگىشلىك ئىشلار:

1.تاھىرجان،ماھىرجاننىڭ ئامېرىكادىكى ئۆي،ئوقۇش،تۇرمۇش مەسلىسىنى ھەل قىلىش، ئابدۇقەييۇم ئېنىمىزنىڭ مەكتەپكە كىرىش تەييارلىق مەسللىرىگە كۆڭۈل بۆلۈش،ئابلىكىمجاننىڭ تۈر تەشەببۇسى ۋە تۈرلىرىنى مۇھاكىمە قىلىش ۋە ئامېرىكا كېلىش مەسلىسنى ئورتاقلىشىش
ۋاقىت قەرەلى 10 كۈن 
(08/01/17 - - - 08/10/17)

2.ھازىرقى بار ئەمەلىي كۈچىمىز ۋە ئەمەلىي قىلالايدىغان ئ‍ىشلىرىمىزنى يغىپ رەتلەش،يۇمشاق دىتال ،تور بەت ياساش قاتارلىق تىز ئۈنۈم كۆرستىدىغان ۋە پۇل تاپقىلى بولدىغان خىزمەتلەر ئۈچۈن بازار ئىچىش ۋە خېرىدار تىپىش ئىشلىرىنى كېڭەيتىش ،ئەسلى بار بولغان توربەتكە مۇناسىپ ئۆزگەرتىش كىرگۈزۈش
ۋاقىت قەرەلى 10 كۈن 
(08/01/17 - - - 08/10/17)

3.چاقماق تۈرىنىڭ ئومۇىي پىلاننى يىزىش، قۇرۇلمسىنى ياساش،تەجرىبە سىناقلاردىن ئۆتكۈزۈپ 1.0 كوردىنات نۇسخىسنى پۈتتۈرۈش ۋە
 PDF
سىنى يىزىپ چىقىپ مەبلەغ سېلىش بازىرىدا مەبلەغ قىزىقتۇرۇش،مەبلەغ سالغۇچى ئىزدەش.
ۋاقىت قەرەلى  30 كۈن 
(08/01/17 - - - 09/01/17)

4.تاۋۇش مەكتەپ تۈرىنى داۋاملاشتۇرۇش ،قۇززات بىلەن كۆرۈشۈپ ياخشى ھەمكارلىق ئ‍ورنىتىش ئۈچۈن ئىزدىنىش،مەكتەپ ئېچىش تۈر پىلاننى قايتىدىن مۇھاكىمە قىلىپ بىكىتىش ،مەكتەپنى ئامال بار ئېچىش .
ۋاقىت قەرەلى  30 كۈن 
(08/01/17 - - - 09/01/17)

5.ئاشخانا تۈرىنى پىلانلاش پەقەتلا پولونى ئاساس قىلغان كىچك ھەم سۈرئەتنى ئاساس قىلغان بۇ ئاشخانا تۈرىنى كىڭەيتىش ئۈچۈن لاھىيە يىزىش،تەننەرىخ ھېساپلاش ۋە تېخىنىكا جەھەتتىكى بارلىق توسالغۇلارنى يىڭىش،ئاشخاننى ئېچىش تەييارلىقىنى قىلىش.
ۋاقىت قەرەلى  30 كۈن 
(08/01/17 - - - 09/01/17)

6.يۇقارىقى مەسلىلەر ھەل بولغاندىن كىين ياكى ھەل بولۇشتىن بۇرۇن يەنە مەسىللەر پەيدا بولسا بۇ ئىششۇ يەنى سەھىپە يىڭىلىندۇ.
